#BNF+IAT 1.0;
!grammer merge_res;

!slot <howToPlay>;
!slot <CollectionCollectionCollectionCollectionCollection>;
!slot <prePlayCollection>;
!slot <stableSpeech>;
!slot <prePlaySong>;
!slot <SongsSongsSongsSongsSongs>;
!slot <bnfFileName>;

!start <merge_resStart>;
<merge_resStart>:
(<CollectionCollectionCollectionCollectionCollection>)|
(<prePlayCollection> <stableSpeech>)|
(<prePlayCollection> [<stableSpeech> | <prePlayCollection>] <stableSpeech>)|
(<CollectionCollectionCollectionCollectionCollection> <prePlayCollection>)|
(<howToPlay>)|
(<SongsSongsSongsSongsSongs>)|
(<prePlaySong> <SongsSongsSongsSongsSongs>);

<howToPlay>:
"<prePlayCollection>|<stableSpeech>";

<CollectionCollectionCollectionCollectionCollection>:
"collections"|
"please"|
"collection";

<prePlayCollection>:
"navigate to"|
"turn to";

<stableSpeech>:
"please col"|
"please";

<prePlaySong>:
"listen"|
"turn to";

<SongsSongsSongsSongsSongs>:
"song"|
"songs";

<bnfFileName>:
"speech_col_test.bnf"|
"speech_songs_test.bnf";

